<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Attendance Correction Request</title>
    <style>
        body { font-family: DejaVu Sans, sans-serif; font-size: 12px; color: #1f2937; line-height: 1.55; }
        .header { text-align: center; margin-bottom: 20px; border-bottom: 2px solid #0d9488; padding-bottom: 10px; }
        .header h1 { margin: 0; font-size: 18px; color: #0d9488; }
        .header p { margin: 4px 0 0; font-size: 11px; color: #6b7280; }
        .ref { text-align: right; font-size: 11px; color: #6b7280; margin-bottom: 15px; }
        .title { text-align: center; font-size: 15px; font-weight: bold; margin: 15px 0 20px; text-transform: uppercase; letter-spacing: 1px; }
        table.info { width: 100%; margin-bottom: 15px; border-collapse: collapse; }
        table.info td { padding: 5px 8px; vertical-align: top; border: 1px solid #e5e7eb; }
        table.info td.label { background: #f9fafb; font-weight: 600; width: 32%; }
        .reason-box { background: #f9fafb; padding: 12px; border-left: 3px solid #0d9488; margin: 15px 0; }
        .sig { margin-top: 60px; }
        .sig-line { border-top: 1px solid #1f2937; width: 80%; padding-top: 4px; font-size: 11px; }
        .footer { position: fixed; bottom: 20px; left: 0; right: 0; text-align: center; font-size: 9px; color: #9ca3af; }
    </style>
</head>
<body>
    <div class="header">
        <h1>OJT Attendance Correction Request</h1>
        <p>Generated by the Internship Management System</p>
    </div>

    <div class="ref">
        Reference No: <strong>AR-{{ str_pad($request->id, 6, '0', STR_PAD_LEFT) }}</strong><br>
        Generated: {{ $generated_at }}
    </div>

    <div class="title">Request for Attendance Correction</div>

    <table class="info">
        <tr>
            <td class="label">Trainee Name</td>
            <td>{{ $trainee->full_name }}</td>
        </tr>
        <tr>
            <td class="label">Department</td>
            <td>{{ $department?->name ?? 'N/A' }}</td>
        </tr>
        <tr>
            <td class="label">Date of Attendance</td>
            <td>{{ $date }}</td>
        </tr>
        <tr>
            <td class="label">Requested Records</td>
            <td>
                <ul style="margin: 0; padding-left: 16px;">
                    @foreach ($fields as $label)
                        <li>{{ $label }}</li>
                    @endforeach
                </ul>
            </td>
        </tr>
    </table>

    <p>To Whom It May Concern,</p>

    <p>
        I, <strong>{{ $trainee->full_name }}</strong>, hereby request a correction of my attendance record for
        <strong>{{ $date }}</strong> due to incomplete data captured by the system. The specific attendance
        entries listed above were not recorded and are the subject of this request.
    </p>

    @if ($request->reason)
        <div class="reason-box">
            <strong>Reason / Explanation:</strong><br>
            {{ $request->reason }}
        </div>
    @endif

    <p>
        I confirm that the information above is accurate and truthful. I respectfully request your approval
        and signature to validate this attendance correction.
    </p>

    <div class="sig">
        <table style="width: 100%;">
            <tr>
                <td style="width: 50%;">
                    <div class="sig-line">
                        <strong>{{ $trainee->full_name }}</strong><br>
                        Trainee Signature
                    </div>
                </td>
                <td style="width: 50%;">
                    <div class="sig-line">
                        &nbsp;<br>
                        Supervisor Signature / Date
                    </div>
                </td>
            </tr>
        </table>
    </div>

    <p style="margin-top: 40px; font-size: 11px; color: #6b7280;">
        <strong>Instructions:</strong> Print this letter, have it signed by your immediate supervisor,
        take a clear photo of the signed letter, and upload it through the system to complete your request.
    </p>

    <div class="footer">
        This document was generated electronically. Reference No. AR-{{ str_pad($request->id, 6, '0', STR_PAD_LEFT) }}
    </div>
</body>
</html>